import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    nursery: "off",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  overrides: [
    {
      files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts"],
      plugins: ["vitest"],
      rules: {
        "eslint-plugin-vitest/prefer-strict-boolean-matchers": "off",
        "eslint-plugin-vitest/prefer-to-be-falsy": "off",
        "eslint-plugin-vitest/prefer-to-be-truthy": "off",
        "typescript/no-explicit-any": "off",
        "vitest/prefer-strict-boolean-matchers": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-truthy": "off",
      },
    },

    {
      files: ["packages/php-composer-upgrade-advisor/**/*.ts"],
      rules: {
        complexity: "off",
        "eslint-plugin-vitest/prefer-strict-boolean-matchers": "off",
        "eslint-plugin-vitest/prefer-to-be-falsy": "off",
        "eslint-plugin-vitest/prefer-to-be-truthy": "off",
        "func-style": "off",
        "id-length": "off",
        "import/exports-last": "off",
        "import/group-exports": "off",
        "import/no-nodejs-modules": "off",
        "init-declarations": "off",
        "max-lines": "off",
        "max-lines-per-function": "off",
        "max-params": "off",
        "max-statements": "off",
        "no-await-in-loop": "off",
        "no-continue": "off",
        "no-magic-numbers": "off",
        "no-nested-ternary": "off",
        "no-plusplus": "off",
        "no-undefined": "off",
        "no-use-before-define": "off",
        "prefer-destructuring": "off",
        "require-await": "off",
        "sort-imports": "off",
        "sort-keys": "off",
        "typescript/consistent-type-definitions": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-call": "off",
        "typescript/no-unsafe-member-access": "off",
        "typescript/no-unsafe-type-assertion": "off",
        "typescript/require-await": "off",
        "typescript/strict-boolean-expressions": "off",
        "unicorn/no-array-sort": "off",
        "unicorn/no-immediate-mutation": "off",
        "unicorn/no-nested-ternary": "off",
        "unicorn/prefer-response-static-json": "off",
        "unicorn/prefer-string-replace-all": "off",
        "unicorn/prefer-top-level-await": "off",
        "vitest/prefer-strict-boolean-matchers": "off",
        "vitest/prefer-to-be-falsy": "off",
        "vitest/prefer-to-be-truthy": "off",
      },
    },
    {
      files: ["**/*.vue"],
      plugins: ["vue"],
      rules: {
        "unicorn/filename-case": "off",
      },
    },
    {
      files: ["**/*.config.ts", "**/*.config.js", "**/worker.ts", "**/src/index.ts"],
      rules: {
        "import/no-default-export": "off",
      },
    },
    {
      files: ["**/sw.js"],
      rules: {
        "import/unambiguous": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-call": "off",
        "typescript/no-unsafe-member-access": "off",
        "typescript/no-unsafe-return": "off",
        "typescript/no-unsafe-type-assertion": "off",
      },
    },
    {
      files: ["**/env.d.ts", "**/*.d.ts"],
      rules: {
        "import/unambiguous": "off",
      },
    },
  ],
  plugins: ["typescript", "import", "unicorn"],
  rules: {
    "import/no-cycle": "error",
    "import/no-duplicates": "error",
    "import/no-named-export": "off",
    "import/no-relative-parent-imports": "off",
    "import/no-self-import": "error",
    "import/no-unassigned-import": "off",
    "import/prefer-default-export": "off",
    "no-duplicate-imports": "off",
    "no-extra-semi": "off",
    "no-mixed-spaces-and-tabs": "off",
    "no-ternary": "off",
    "typescript/no-explicit-any": "error",
    "typescript/no-non-null-assertion": "error",
    "unicorn/no-null": "off",
  },
});
